### ISSUE TITLE
Question: does this incorporate summer hours/DST?

### ISSUE THREAD

**Issue by acroyear** [medikoo/date-from-timezone#1]
Not a 'bug', I'm just asking before I look to consider this in a current project.

**Comment by medikoo** [comment]
@acroyear yes. It retrieves data from database that lives with `Intl`, and DST resolve as expected.

See these tests: [test/index.js#L23-L24](https://github.com/medikoo/date-from-timezone/blob/7bd00f8b2a2e0b5162eafb12627751219c30b5d7/test/index.js#L23-L24), they pass in all major engines
