### ISSUE TITLE
Module parse failed: 'return' outside of function with webpack and babel

### ISSUE THREAD

**Issue by pbadenski** [medikoo/date-from-timezone#2]
Not quite sure if I'm doing something wrong but when requiring this library with webpack and babel I'm getting:

```
ERROR in ./node_modules/date-from-timezone/index.js 10:1
    Module parse failed: 'return' outside of function (10:1)
    You may need an appropriate loader to handle this file type.
    | if (!getTokenize) {
    | 	module.exports = null;
    > 	return;
    | }
```

**Comment by medikoo** [comment]
Technically it's perfectly valid CJS module, so either it's some configuration error on your side or parser bug

I suggest to ask question on stackoverflow with `webpack` and `babel`label, or if it's clear it's an issue with bundler open a bug in webpack bug tracker.

**Comment by jlcarvalho** [comment]
This issue https://github.com/babel/babel/issues/1298 explains the reason of the error.
